version : '3.7'

services:
    app:
      build: ./.docker
      working_dir: /var/www
      volumes:
        - .:/var/www:cached
        - ./.docker/php.ini:/usr/local/etc/php/conf.d/local.ini
      networks:
        - soap-network

    nginx:
      image: nginx:alpine
      ports:
        - "8000:8080"
      volumes:
        - .:/var/www:cached
        - ./.docker/app.conf:/etc/nginx/conf.d/app.conf
      networks:
        - soap-network

    db:
      image: mysql:8
      ports:
        - "3309:3306"
      networks:
        - soap-network
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: app

    redis:
      image: 'redis:alpine'
      ports:
        - '6383:6379'
      networks:
        - soap-network
        
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
        - "8183:80"
      environment:
        PMA_HOST: db
        PMA_USER: root
        PMA_PASSWORD: root
      networks:
        - soap-network

networks:
  soap-network:
    driver: bridge
